services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: questdo
      POSTGRES_PASSWORD: questdo
      POSTGRES_DB: questdo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      DATABASE_URL: postgresql://questdo:questdo@db:5432/questdo
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
